-- AlterTable
ALTER TABLE "CommunitySettings" ADD COLUMN IF NOT EXISTS "gamifyPointsPost" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "CommunitySettings" ADD COLUMN IF NOT EXISTS "gamifyPointsComment" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "CommunitySettings" ADD COLUMN IF NOT EXISTS "gamifyPointsLike" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "CommunitySettings" ADD COLUMN IF NOT EXISTS "gamifyPointsLesson" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "CommunitySettings" ADD COLUMN IF NOT EXISTS "gamifyLevelThresholds" TEXT NOT NULL DEFAULT '0,50,120,210,320,450,600,770,960,1170';
